from triage import triage_email
from tools import check_calendar_availability, schedule_meeting, write_email
from datetime import datetime

def react_agent(email_text: str):
    print(f"Incoming Email: {email_text}")
    print("-" * 30)
    
    decision = triage_email(email_text)
    print(f"Triage decision: {decision}")

    if decision != "respond/act":
        print("No further action required.")
        return

    print("Reasoning...")
    email_lower = email_text.lower()
    
    # Simple keyword-based routing for demonstration
    # In a real LangGraph implementation, this would be determined by the LLM
    
    if "schedule" in email_lower or "meeting" in email_lower:
        print("Action detected: Schedule/Check Calendar")
        # Extract date (mock extraction for now, usually done by LLM)
        # Assuming "tomorrow" for simplicity if not specified, or today
        target_date = datetime.now().strftime("%Y-%m-%d")
        
        print(f"Action: check_calendar_availability('{target_date}')")
        availability = check_calendar_availability(target_date)
        print(f"Result: {availability}")
        
        if "schedule" in email_lower:
            # Mock scheduling logic
            print("Action: schedule_meeting(...)")
            print("Please confirm details to proceed with scheduling.")
            # In a full agent, we'd call schedule_meeting here
            
    elif "send" in email_lower or "write" in email_lower or "email" in email_lower:
        print("Action detected: Send Email")
        # Mock extraction
        to_address = "test@example.com"
        subject = "Re: Your message"
        content = "This is a response generated by the agent."
        
        print(f"Action: write_email('{to_address}', '{subject}', ...)")
        # Uncomment to actually send when credentials are ready
        # result = write_email(to_address, subject, content)
        # print(f"Result: {result}")
        print("Email sending logic is ready (commented out for safety until config is verified).")

    else:
        print("Agent could not determine a specifc tool action.")
