emails = [
    "From: college@university.edu\nSubject: Exam timetable for next week",
    "From: hr@company.com\nSubject: Interview scheduled for Monday",
    "From: offers@shopping.com\nSubject: 70% discount on electronics",
    "From: spam@lottery.com\nSubject: You won a million dollars",
    "From: professor@university.edu\nSubject: Assignment submission deadline",
    "From: friend@gmail.com\nSubject: Can we meet tomorrow?",
    "From: amazon@amazon.in\nSubject: Your order has been shipped",
    "From: training@internship.com\nSubject: Session reminder for today",
    "From: bank@icici.com\nSubject: Your monthly account statement",
    "From: promo@store.com\nSubject: Buy one get one free",

    "From: college@university.edu\nSubject: Internal exam venue announced",
    "From: hr@company.com\nSubject: Offer letter discussion",
    "From: deals@shopping.com\nSubject: Big billion days sale",
    "From: spam@casino.com\nSubject: Free casino credits",
    "From: professor@university.edu\nSubject: Project review meeting",
    "From: friend@gmail.com\nSubject: Birthday party invitation",
    "From: flipkart@flipkart.com\nSubject: Your item is out for delivery",
    "From: training@internship.com\nSubject: Attendance required today",
    "From: bank@sbi.com\nSubject: Credit card bill due",
    "From: promo@store.com\nSubject: Flash sale ends tonight",

    "From: college@university.edu\nSubject: Practical exam schedule",
    "From: hr@company.com\nSubject: Interview feedback",
    "From: offers@shopping.com\nSubject: Clearance sale",
    "From: spam@prize.com\nSubject: Claim your prize now",
    "From: professor@university.edu\nSubject: Research paper submission",
    "From: friend@gmail.com\nSubject: Trip planning",
    "From: myntra@myntra.com\nSubject: Your refund has been processed",
    "From: training@internship.com\nSubject: Final evaluation details",
    "From: bank@hdfc.com\nSubject: Loan EMI reminder",
    "From: promo@store.com\nSubject: Exclusive member discount",

    "From: college@university.edu\nSubject: Semester result announced",
    "From: hr@company.com\nSubject: HR policy update",
    "From: deals@shopping.com\nSubject: Weekend mega sale",
    "From: spam@ads.com\nSubject: Earn money fast",
    "From: professor@university.edu\nSubject: Viva voce schedule",
    "From: friend@gmail.com\nSubject: Lunch tomorrow?",
    "From: amazon@amazon.in\nSubject: Delivery delayed",
    "From: training@internship.com\nSubject: Project demo reminder",
    "From: bank@axis.com\nSubject: Debit card usage alert",
    "From: promo@store.com\nSubject: Limited time offer"
]
